# Generated by Django 5.0.6 on 2024-06-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
