# Generated by Django 5.0.6 on 2024-06-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='ONum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
