# Generated by Django 5.0.6 on 2024-06-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_section_onum_section_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Course_id', models.IntegerField()),
                ('Section_id', models.IntegerField()),
            ],
        ),
    ]
