# Generated by Django 5.0.6 on 2024-06-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='Title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='section',
            name='Title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
