# Generated by Django 5.0.6 on 2024-06-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='folder_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
