# Generated by Django 5.0.6 on 2024-07-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='folder_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
