# Generated by Django 5.0.6 on 2024-07-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_assignment_folder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='folder_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
