# Generated by Django 5.0.6 on 2024-07-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_alter_uploadedfile_folder_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='folder_id',
        ),
        migrations.AddField(
            model_name='folder',
            name='Files',
            field=models.ManyToManyField(blank=True, to='portal.uploadedfile'),
        ),
    ]
