# Generated by Django 5.0.6 on 2024-07-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_remove_uploadedfile_folder_id_folder_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='Section_id',
        ),
        migrations.AddField(
            model_name='section',
            name='Folders',
            field=models.ManyToManyField(blank=True, to='portal.uploadedfile'),
        ),
    ]
