# Generated by Django 5.0.6 on 2024-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_remove_folder_section_id_section_folders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='Folders',
            field=models.ManyToManyField(blank=True, to='portal.folder'),
        ),
    ]
