# Generated by Django 5.0.6 on 2024-08-10 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_filestoassignment_assignment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestoassignment',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
