# Generated by Django 5.0.6 on 2024-08-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_filestoassignment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
