# Generated by Django 5.0.6 on 2024-08-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='course_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
