# Generated by Django 5.0.6 on 2024-08-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
