# Generated by Django 5.0.6 on 2024-08-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_customuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
