# Generated by Django 5.0.6 on 2024-08-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_customuser_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='carousel_images/')),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
