# Generated by Django 5.0.6 on 2024-08-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_carouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='order',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
