# Generated by Django 5.0.6 on 2024-08-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_alter_carouselimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimage',
            options={},
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
