# Generated by Django 5.0.6 on 2024-12-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_alter_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
