# Generated by Django 5.0.6 on 2024-12-31 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.courses'),
            preserve_default=False,
        ),
    ]
