# Generated by Django 5.0.6 on 2025-01-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_alter_uploadedattendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedattendance',
            name='file',
            field=models.FileField(upload_to='attendance/'),
        ),
    ]
