# Generated by Django 5.0.6 on 2025-01-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_alter_uploadedattendance_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedattendance',
            name='student',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
