# Generated by Django 5.0.6 on 2025-01-01 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_alter_uploadedattendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
