# Generated by Django 5.1.4 on 2025-02-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0047_customuser_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='modified_profile_photo',
            field=models.BooleanField(default=False),
        ),
    ]
