# Generated by Django 5.1.4 on 2025-02-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0048_alter_customuser_modified_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='modified_profile_photo',
            field=models.BooleanField(default=True),
        ),
    ]
