# Generated by Django 5.1.4 on 2025-03-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0049_alter_customuser_modified_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(max_length=50)),
                ('organizer', models.CharField(blank=True, help_text='Organizer information (max 500 characters)', max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_scheduled', models.DateTimeField(blank=True, null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
