# Generated by Django 5.1.4 on 2025-03-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0050_weeklyemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyemail',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weeklyemail',
            name='date_scheduled',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyemail',
            name='date_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
