# Generated by Django 5.1.4 on 2025-03-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0051_alter_weeklyemail_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
