"""Create, list, or delete managed table copies in PostgreSQL or MySQL.

Usage:
    python database_table_backup.py
    python database_table_backup.py create
    python database_table_backup.py list
    python database_table_backup.py delete

``delete`` only drops tables recorded in this utility's manifest. Original
application tables are never eligible for deletion.
"""

import argparse
from contextlib import nullcontext
import os
import sys
import uuid

import django


MANIFEST_TABLE = "_table_backup_manifest"
BACKUP_PREFIX = "_table_backup_"
POSTGRES_LOCK_ID = 7_316_420_117
MYSQL_LOCK_NAME = "gurmukhischool_table_backup"
SUPPORTED_DATABASES = {"postgresql", "mysql"}


def configure_django():
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "gurmukhischool.settings")
    django.setup()


def quote(connection, identifier):
    return connection.ops.quote_name(identifier)


def require_supported_database(connection):
    if connection.vendor not in SUPPORTED_DATABASES:
        raise RuntimeError(
            "This utility supports PostgreSQL and MySQL; "
            f"the configured database is {connection.vendor!r}."
        )


def table_exists(connection, table_name):
    with connection.cursor() as cursor:
        return table_name in connection.introspection.table_names(cursor)


def acquire_lock(connection):
    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            cursor.execute(
                "SELECT pg_advisory_xact_lock(%s)",
                [POSTGRES_LOCK_ID],
            )
        else:
            cursor.execute("SELECT GET_LOCK(%s, %s)", [MYSQL_LOCK_NAME, 30])
            if cursor.fetchone()[0] != 1:
                raise RuntimeError("Could not acquire the MySQL backup lock.")


def release_lock(connection):
    if connection.vendor != "mysql":
        return
    with connection.cursor() as cursor:
        cursor.execute("SELECT RELEASE_LOCK(%s)", [MYSQL_LOCK_NAME])


def create_manifest(connection):
    manifest = quote(connection, MANIFEST_TABLE)
    if connection.vendor == "postgresql":
        id_column = "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        timestamp_column = "timestamptz"
    else:
        id_column = "bigint AUTO_INCREMENT PRIMARY KEY"
        timestamp_column = "timestamp"

    with connection.cursor() as cursor:
        cursor.execute(
            f"""
            CREATE TABLE IF NOT EXISTS {manifest} (
                id {id_column},
                run_id varchar(32) NOT NULL,
                source_schema varchar(63) NOT NULL,
                source_table varchar(63) NOT NULL,
                backup_table varchar(63) NOT NULL UNIQUE,
                copied_rows bigint NOT NULL,
                created_at {timestamp_column} NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )


def source_tables(connection):
    with connection.cursor() as cursor:
        names = connection.introspection.table_names(cursor)

    names = sorted(
        name
        for name in names
        if name != MANIFEST_TABLE and not name.startswith(BACKUP_PREFIX)
    )
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute("SELECT current_schema()")
            schema_name = cursor.fetchone()[0]
    else:
        schema_name = connection.settings_dict["NAME"]
    return [(schema_name, name) for name in names]


def qualified_table(connection, schema_name, table_name):
    return (
        f"{quote(connection, schema_name)}."
        f"{quote(connection, table_name)}"
    )


def clone_empty_table(connection, schema_name, source_name, backup_name):
    source = qualified_table(connection, schema_name, source_name)
    backup = quote(connection, backup_name)
    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            cursor.execute(
                f"CREATE TABLE {backup} (LIKE {source} INCLUDING ALL)"
            )
        else:
            cursor.execute(f"CREATE TABLE {backup} LIKE {source}")


def add_manifest_row(
    connection,
    run_id,
    schema_name,
    source_name,
    backup_name,
):
    manifest = quote(connection, MANIFEST_TABLE)
    with connection.cursor() as cursor:
        cursor.execute(
            f"""
            INSERT INTO {manifest} (
                run_id,
                source_schema,
                source_table,
                backup_table,
                copied_rows
            )
            VALUES (%s, %s, %s, %s, 0)
            """,
            [run_id, schema_name, source_name, backup_name],
        )


def copy_rows(connection, run_id, tables):
    manifest = quote(connection, MANIFEST_TABLE)
    with connection.cursor() as cursor:
        for schema_name, source_name, backup_name in tables:
            source = qualified_table(connection, schema_name, source_name)
            backup = quote(connection, backup_name)
            cursor.execute(f"INSERT INTO {backup} SELECT * FROM {source}")
            copied_rows = cursor.rowcount
            cursor.execute(
                f"""
                UPDATE {manifest}
                SET copied_rows = %s
                WHERE run_id = %s AND backup_table = %s
                """,
                [copied_rows, run_id, backup_name],
            )
            print(f"Copied {source_name}: {copied_rows} rows")


def cleanup_failed_run(connection, run_id, backup_names):
    manifest = quote(connection, MANIFEST_TABLE)
    with connection.cursor() as cursor:
        for backup_name in reversed(backup_names):
            cursor.execute(
                f"DROP TABLE IF EXISTS {quote(connection, backup_name)}"
            )
        if table_exists(connection, MANIFEST_TABLE):
            cursor.execute(
                f"DELETE FROM {manifest} WHERE run_id = %s",
                [run_id],
            )


def create_backups(connection):
    from django.db import transaction

    run_id = uuid.uuid4().hex[:12]
    create_manifest(connection)
    sources = source_tables(connection)
    if not sources:
        print("No source tables were found.")
        return

    planned = []
    try:
        for position, (schema_name, source_name) in enumerate(
            sources,
            start=1,
        ):
            backup_name = f"{BACKUP_PREFIX}{run_id}_{position:04d}"
            clone_empty_table(
                connection,
                schema_name,
                source_name,
                backup_name,
            )
            add_manifest_row(
                connection,
                run_id,
                schema_name,
                source_name,
                backup_name,
            )
            planned.append((schema_name, source_name, backup_name))

        # On MySQL, table DDL commits implicitly. Creating all empty tables
        # first lets the subsequent row copies share one repeatable-read
        # snapshot. PostgreSQL keeps both DDL and data inside the outer atomic
        # transaction used by main().
        transaction_context = (
            transaction.atomic()
            if connection.vendor == "mysql"
            else nullcontext()
        )
        with transaction_context:
            if connection.vendor == "mysql":
                with connection.cursor() as cursor:
                    cursor.execute(
                        "SET TRANSACTION ISOLATION LEVEL REPEATABLE READ"
                    )
            copy_rows(connection, run_id, planned)
    except Exception:
        if connection.vendor == "mysql":
            cleanup_failed_run(
                connection,
                run_id,
                [item[2] for item in planned],
            )
        raise

    print(f"Backup run {run_id} completed: {len(planned)} tables copied.")


def list_backups(connection):
    if not table_exists(connection, MANIFEST_TABLE):
        print("No managed backup tables exist.")
        return

    manifest = quote(connection, MANIFEST_TABLE)
    with connection.cursor() as cursor:
        cursor.execute(
            f"""
            SELECT
                run_id,
                source_table,
                backup_table,
                copied_rows,
                created_at
            FROM {manifest}
            ORDER BY created_at, source_table
            """
        )
        rows = cursor.fetchall()

    if not rows:
        print("No managed backup tables exist.")
        return
    for run_id, source, backup, row_count, created_at in rows:
        print(
            f"{run_id}  {source} -> {backup}  "
            f"({row_count} rows, {created_at})"
        )


def delete_backups(connection):
    if not table_exists(connection, MANIFEST_TABLE):
        print("No managed backup tables exist.")
        return

    manifest = quote(connection, MANIFEST_TABLE)
    with connection.cursor() as cursor:
        cursor.execute(f"SELECT backup_table FROM {manifest} ORDER BY id DESC")
        backup_tables = [row[0] for row in cursor.fetchall()]

        for backup_table in backup_tables:
            if not backup_table.startswith(BACKUP_PREFIX):
                raise RuntimeError(
                    f"Refusing to drop unexpected table {backup_table!r}."
                )
            cursor.execute(
                f"DROP TABLE IF EXISTS {quote(connection, backup_table)}"
            )
            print(f"Deleted {backup_table}")

        cursor.execute(f"DROP TABLE {manifest}")

    print(f"Deleted {len(backup_tables)} managed backup tables and the manifest.")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Manage PostgreSQL or MySQL table copies."
    )
    parser.add_argument(
        "command",
        nargs="?",
        default="create",
        choices=("create", "list", "delete"),
        help="Create, list, or delete the managed backup tables.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    configure_django()

    from django.db import connection, transaction

    require_supported_database(connection)
    postgres_context = (
        transaction.atomic()
        if connection.vendor == "postgresql"
        else nullcontext()
    )
    try:
        with postgres_context:
            if connection.vendor == "postgresql":
                with connection.cursor() as cursor:
                    cursor.execute(
                        "SET TRANSACTION ISOLATION LEVEL REPEATABLE READ"
                    )
            acquire_lock(connection)
            if args.command == "create":
                create_backups(connection)
            elif args.command == "list":
                list_backups(connection)
            else:
                delete_backups(connection)
    except Exception as exc:
        print(f"Backup operation failed: {exc}", file=sys.stderr)
        return 1
    finally:
        try:
            release_lock(connection)
        except Exception as exc:
            print(
                f"Warning: could not release the database lock: {exc}",
                file=sys.stderr,
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
