"""Create or delete PostgreSQL backup copies of the project's database tables.

Usage:
    python database_table_backup.py
    python database_table_backup.py create
    python database_table_backup.py list
    python database_table_backup.py delete

The ``delete`` command only drops tables recorded in this script's manifest.
It never drops an original application table.
"""

import argparse
import os
import sys
import uuid

import django


MANIFEST_TABLE = "_table_backup_manifest"
BACKUP_PREFIX = "_table_backup_"
LOCK_ID = 7_316_420_117


def configure_django():
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "gurmukhischool.settings")
    django.setup()


def quote(connection, identifier):
    return connection.ops.quote_name(identifier)


def require_postgresql(connection):
    if connection.vendor != "postgresql":
        raise RuntimeError(
            "This utility supports PostgreSQL only; "
            f"the configured database is {connection.vendor!r}."
        )


def create_manifest(cursor, connection):
    manifest = quote(connection, MANIFEST_TABLE)
    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {manifest} (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id varchar(32) NOT NULL,
            source_schema varchar(63) NOT NULL,
            source_table varchar(63) NOT NULL,
            backup_table varchar(63) NOT NULL UNIQUE,
            copied_rows bigint NOT NULL,
            created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )


def source_tables(cursor):
    cursor.execute(
        """
        SELECT schemaname, tablename
        FROM pg_catalog.pg_tables
        WHERE schemaname = current_schema()
          AND tablename <> %s
          AND tablename NOT LIKE %s
        ORDER BY tablename
        """,
        [MANIFEST_TABLE, f"{BACKUP_PREFIX}%"],
    )
    return cursor.fetchall()


def create_backups(connection):
    run_id = uuid.uuid4().hex[:12]

    with connection.cursor() as cursor:
        cursor.execute("SELECT pg_advisory_xact_lock(%s)", [LOCK_ID])
        create_manifest(cursor, connection)
        tables = source_tables(cursor)
        if not tables:
            print("No source tables were found.")
            return

        manifest = quote(connection, MANIFEST_TABLE)
        for position, (schema_name, table_name) in enumerate(tables, start=1):
            # The generated name stays under PostgreSQL's 63-byte identifier limit.
            backup_name = f"{BACKUP_PREFIX}{run_id}_{position:04d}"
            source = (
                f"{quote(connection, schema_name)}."
                f"{quote(connection, table_name)}"
            )
            backup = quote(connection, backup_name)

            cursor.execute(f"CREATE TABLE {backup} (LIKE {source} INCLUDING ALL)")
            cursor.execute(f"INSERT INTO {backup} SELECT * FROM {source}")
            copied_rows = cursor.rowcount
            cursor.execute(
                f"""
                INSERT INTO {manifest} (
                    run_id,
                    source_schema,
                    source_table,
                    backup_table,
                    copied_rows
                )
                VALUES (%s, %s, %s, %s, %s)
                """,
                [
                    run_id,
                    schema_name,
                    table_name,
                    backup_name,
                    copied_rows,
                ],
            )
            print(f"Copied {table_name}: {copied_rows} rows")

    print(f"Backup run {run_id} completed: {len(tables)} tables copied.")


def list_backups(connection):
    with connection.cursor() as cursor:
        cursor.execute("SELECT to_regclass(%s)", [MANIFEST_TABLE])
        if cursor.fetchone()[0] is None:
            print("No managed backup tables exist.")
            return

        manifest = quote(connection, MANIFEST_TABLE)
        cursor.execute(
            f"""
            SELECT
                run_id,
                source_table,
                backup_table,
                copied_rows,
                created_at
            FROM {manifest}
            ORDER BY created_at, source_table
            """
        )
        rows = cursor.fetchall()
        if not rows:
            print("No managed backup tables exist.")
            return
        for run_id, source, backup, row_count, created_at in rows:
            print(
                f"{run_id}  {source} -> {backup}  "
                f"({row_count} rows, {created_at})"
            )


def delete_backups(connection):
    with connection.cursor() as cursor:
        cursor.execute("SELECT pg_advisory_xact_lock(%s)", [LOCK_ID])
        cursor.execute("SELECT to_regclass(%s)", [MANIFEST_TABLE])
        if cursor.fetchone()[0] is None:
            print("No managed backup tables exist.")
            return

        manifest = quote(connection, MANIFEST_TABLE)
        cursor.execute(f"SELECT backup_table FROM {manifest} ORDER BY id DESC")
        backup_tables = [row[0] for row in cursor.fetchall()]

        for backup_table in backup_tables:
            if not backup_table.startswith(BACKUP_PREFIX):
                raise RuntimeError(
                    f"Refusing to drop unexpected table {backup_table!r}."
                )
            cursor.execute(
                f"DROP TABLE IF EXISTS {quote(connection, backup_table)}"
            )
            print(f"Deleted {backup_table}")

        cursor.execute(f"DROP TABLE {manifest}")

    print(f"Deleted {len(backup_tables)} managed backup tables and the manifest.")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Manage transactionally consistent PostgreSQL table copies."
    )
    parser.add_argument(
        "command",
        nargs="?",
        default="create",
        choices=("create", "list", "delete"),
        help="Create, list, or delete the managed backup tables.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    configure_django()

    from django.db import connection, transaction

    require_postgresql(connection)
    try:
        with transaction.atomic():
            with connection.cursor() as cursor:
                cursor.execute(
                    "SET TRANSACTION ISOLATION LEVEL REPEATABLE READ"
                )
            if args.command == "create":
                create_backups(connection)
            elif args.command == "list":
                list_backups(connection)
            else:
                delete_backups(connection)
    except Exception as exc:
        print(f"Backup operation failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
