# Generated by Django 5.1.4 on 2025-04-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contact_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
