# Generated by Django 5.1.4 on 2025-04-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blacklistedip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedip',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
